<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>PeopleSoft PeopleCode Call Stack</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#callstack</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>callstack</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#session</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#methods</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#events</string>
				</dict>
			</array>
		</dict>
		<key>events</key>
		<dict>
			<key>name</key>
			<string>meta.event.pcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(start|resume)\s+?(.*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pcode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.pcode</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\n)</string>
					<key>name</key>
					<string>meta.method.event.pcode</string>
				</dict>
			</array>
		</dict>
		<key>methods</key>
		<dict>
			<key>name</key>
			<string>meta.method.pcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(call (?:method|function|getter|setter))\s+?(.*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pcode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.pcode</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\n)</string>
					<key>name</key>
					<string>meta.method.identifier.pcode</string>
				</dict>
			</array>
		</dict>
		<key>session</key>
		<dict>
			<key>name</key>
			<string>meta.method.pcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(Session \d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.pcode</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(:)</string>
					<key>name</key>
					<string>meta.method.session.pcode</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.peoplecode.psoftcallstack</string>
	<key>uuid</key>
	<string>cd1113f9-149f-4e18-9dec-c39a75a7c283</string>
</dict>
</plist>
